services:
  db:
    image: postgres:16
    container_name: incuvera_container
    restart: always
    environment:
      POSTGRES_USER: callmekay
      POSTGRES_PASSWORD: govleadcallmekay@1
      POSTGRES_DB: incuvera_db
    ports:
      - '5433:5433'
    volumes:
      - pgdata:/var/lib/postgresql/data

  # web:
  #   build: .
  #   container_name: nextjs_app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
  #   depends_on:
  #     - db

volumes:
  pgdata:
